[project]
name = "dupechecker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
    "pandas-stubs~=3.0.0",
]
